### ISSUE TITLE
[Dhawa] Complete CSS for Button component

### ISSUE THREAD

**Issue by Sabita9818** [steamnp/bfs45#14]
Write CSS for all classes and create responsive button

Convert to CSS module

**Comment by dhawasangbolama2** [comment]
![image2](https://github.com/steamnp/bfs45/assets/57231698/85e6400f-5a35-4b56-953b-52f583825c24)
![image1](https://github.com/steamnp/bfs45/assets/57231698/6817eb8f-f5ea-4c93-b1b4-e351d8851323)

**Comment by dhawasangbolama2** [comment]
css completed for all the components
