### ISSUE TITLE
[Satshree and Nima] Function in JavaScript

### ISSUE THREAD

**Issue by Sabita9818** [steamnp/bfs45#24]
1. Write a function in javascript which will add all the odd numbers and give sum of odd numbers.

For example

input: [1,2,3,4,5,6,7,8]

output: 16

1. Write a function in javascript to check weather provided number is prime or not. Return true if it is prime else return false.

For example

input: 1

output: false

input: 2

output: true

input: 49

output: false

**Comment by sherpa2025** [comment]
function App() {
  // function to add odd number of an array
  const addOddNum = () => {
    const number = [1, 2, 3, 4, 5, 6, 7, 8, 11, 12];
    let addNum = 0;
    for (let i = 0; i < number.length; i++) {
      if (number[i] % 2 != 0) {
        addNum = addNum + number[i];
      }
    }
    console.log(number);
    console.log("Addition of odd number from the array: " + addNum);
  };

  // function to check whether the number is prime or not
  const checkPrime = (input) => {
    console.log(input);
    let primeNumber = true;

    if (input == 0 || input == 1) {
      primeNumber = false;
    } else if (input > 1) {
      for (let j = 2; j < input; j++) {
        if (input % j == 0) {
          primeNumber = false;
          break;
        }
      }
    }
    console.log("Is number " + input + " a prime number: " + primeNumber);
  };
  return (
    <>
      <div>
        {addOddNum()}
        {checkPrime(8)}
      </div>
    </>
  );
}

export default App;

**Comment by satshree** [comment]
```javascript
const oddSum = (listOfNumbers) => {
  let sum = 0;

  for (let n of listOfNumbers) {
    if (n % 2 !== 0) sum += n;
  }

  return sum;
};

const isPrime = (num) => {
  if (num < 2) return false;

  let i = 2;

  while (i < num - 1) {
    if (num % i === 0) return false;
    i++;
  }

  return true;
};
