### ISSUE TITLE
[Satshree and Nima] Creating two Pages using React Router DOM

### ISSUE THREAD

**Issue by Sabita9818** [steamnp/bfs45#29]
Create two pages

- `Home` page for all country (show country flag and name of the country)

```jsx
https://restcountries.com/v3.1/all
```

- `Detail` page for each country (display more information)

```jsx
https://restcountries.com/v3.1/name/australia
```

If any country in home page is clicked, the detail page of the corresponding country should open.

**Comment by satshree** [comment]
https://github.com/steamnp/bfs45/tree/satshree

**Comment by sherpa2025** [comment]
**2 pages created with link created with search bar (additional)
Check ReadMe.d in my given repo for more info.**
https://github.com/steamnp/bfs45/tree/nimasherpa
![complete](https://github.com/steamnp/bfs45/assets/79430796/1ca494ac-18bd-4baf-aa56-2e8af6b36423)
