### ISSUE TITLE
[ Sonam and Aashirwad] Global State Management

### ISSUE THREAD

**Issue by Sabita9818** [steamnp/bfs45#32]
Task 1: Use `createSlice` from redux toolkit

Create three button `Increment`, `Decrement`, `Increment by 5`

Initial count value should be `0`

https://redux-toolkit.js.org/tutorials/typescript

Task 2: Use RTK (`createApi` from redux toolkit)

Display first `20` Pokemon in home page

When any Pokemon is clicked, display detail of that Pokemon

https://redux-toolkit.js.org/tutorials/rtk-query

**Comment by aashirwad43** [comment]
Task 1 - Counter Application
https://github.com/steamnp/bfs45/tree/team-Aashirwad-Sonam-counter-app

Task 2 - Pokemon API
https://github.com/steamnp/bfs45/tree/aashirwad-sonam-pokemonAPI
